[project]
name = "csv-flashcard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "Flask==3.0.0",
    "pytest==7.4.3",
    "hypothesis==6.92.1",
]
